version: '3.8'

services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

  admin-service:
    build: ./Admin-Service
    image: gaya2001/admin-service:latest
    container_name: admin-service
    ports:
      - "4999:4999"
    volumes:
      - ./Admin-Service:/app
    env_file:
      - ./Admin-Service/.env
    depends_on:
      - mongo
    networks:
      - app-network

  auth-service:
    build: ./Auth-Service
    image: gaya2001/auth-service:latest
    container_name: auth-service
    ports:
      - "5001:5001"
    volumes:
      - ./Auth-Service:/app
    env_file:
      - ./Auth-Service/.env
    depends_on:
      - mongo
    networks:
      - app-network

  delivery-service:
    build: ./Delivery-Service
    image: gaya2001/delivery-service:latest
    container_name: delivery-service
    ports:
      - "5002:5002"
    volumes:
      - ./Delivery-Service:/app
    env_file:
      - ./Delivery-Service/.env
    depends_on:
      - mongo
    networks:
      - app-network

  order-service:
    build: ./order-management-service
    image: gaya2001/order-service:latest
    container_name: order-service
    ports:
      - "5003:5003"
    volumes:
      - ./order-management-service:/app
    env_file:
      - ./order-management-service/.env
    depends_on:
      - mongo
    networks:
      - app-network

  payment-service:
    build: ./Payment-Service
    image: gaya2001/payment-service:latest
    container_name: payment-service
    ports:
      - "5004:5004"
    volumes:
      - ./Payment-Service:/app
    env_file:
      - ./Payment-Service/.env
    depends_on:
      - mongo
    networks:
      - app-network

  restaurant-service:
    build: ./Restaurant-Service
    image: gaya2001/restaurant-service:latest
    container_name: restaurant-service
    ports:
      - "5005:5005"
    volumes:
      - ./Restaurant-Service:/app
    env_file:
      - ./Restaurant-Service/.env
    depends_on:
      - mongo
    networks:
      - app-network

  user-service:
    build: ./User-Service
    image: gaya2001/user-service:latest
    container_name: user-service
    ports:
      - "5006:5006"
    volumes:
      - ./User-Service:/app
    env_file:
      - ./User-Service/.env
    depends_on:
      - mongo
    networks:
      - app-network

  notification-service:
    build: ./notification-service
    image: gaya2001/notification-service:latest
    container_name: notification-service
    ports:
      - "5007:5007"
    volumes:
      - ./notification-service:/app
    env_file:
      - ./notification-service/.env
    depends_on:
      - mongo
    networks:
      - app-network

  client:
    build: ./Client
    image: gaya2001/client-service:latest
    container_name: client-service
    ports:
      - "5173:5173"
    env_file:
      - ./Client/.env
    volumes:
      - ./Client:/app
      - client_node_modules:/app/node_modules
    depends_on:
      - restaurant-service
      - auth-service
      - admin-service
      - delivery-service
      - order-service
      - payment-service
      - user-service
    stdin_open: true
    tty: true
    networks:
      - app-network

volumes:
  mongo_data:
  client_node_modules:


networks:
  app-network:
    driver: bridge
