apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-service
  namespace: ambula-lk
spec:
  replicas: 2
  selector:
    matchLabels:
      app: admin-service
  template:
    metadata:
      labels:
        app: admin-service
    spec:
      containers:
        - name: admin-service
          image: gaya2001/admin-service:latest
          ports:
            - containerPort: 4999
          env:
            - name: PORT
              value: "4999"
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: admin-service-secret
                  key: MONGO_URI
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: admin-service-secret
                  key: JWT_SECRET
            - name: CLOUDINARY_API_KEY
              valueFrom:
                secretKeyRef:
                  name: admin-service-secret
                  key: CLOUDINARY_API_KEY
            - name: CLOUDINARY_CLOUD_NAME
              valueFrom:
                secretKeyRef:
                  name: admin-service-secret
                  key: CLOUDINARY_CLOUD_NAME

            - name: CLOUDINARY_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: admin-service-secret
                  key: CLOUDINARY_API_SECRET

            - name: GOOGLE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: admin-service-secret
                  key: GOOGLE_API_KEY

            - name: RESTAURANT_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: admin-service-secret
                  key: RESTAURANT_BASE_URL
            - name: CUSTOMER_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: admin-service-secret
                  key: CUSTOMER_BASE_URL
            - name: DELIVERY_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: admin-service-secret
                  key: DELIVERY_BASE_URL
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "200m"

---
apiVersion: v1
kind: Service
metadata:
  name: admin-service
  namespace: ambula-lk
spec:
  selector:
    app: admin-service
  ports:
    - port: 4999
      targetPort: 4999
  type: ClusterIP
