apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery-service
  namespace: ambula-lk
spec:
  replicas: 2
  selector:
    matchLabels:
      app: delivery-service
  template:
    metadata:
      labels:
        app: delivery-service
    spec:
      containers:
        - name: delivery-service
          image: gaya2001/delivery-service:latest
          ports:
            - containerPort: 5002
          env:
            - name: PORT
              value: "5002"
            - name: NODE_ENV
              value: "development"
            - name: UPLOAD_DIR
              value: "uploads"
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: delivery-service-secret
                  key: MONGODB_URI
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: delivery-service-secret
                  key: JWT_SECRET
            - name: CLOUDINARY_API_KEY
              valueFrom:
                secretKeyRef:
                  name: delivery-service-secret
                  key: CLOUDINARY_API_KEY
            - name: CLOUDINARY_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: delivery-service-secret
                  key: CLOUDINARY_API_SECRET
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "200m"

---
apiVersion: v1
kind: Service
metadata:
  name: delivery-service
  namespace: ambula-lk
spec:
  selector:
    app: delivery-service
  ports:
    - port: 5002
      targetPort: 5002
  type: ClusterIP
