apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: ambula-lk
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: gaya2001/order-service:latest
          ports:
            - containerPort: 5003
          env:
            - name: PORT
              value: "5003"
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: order-service-secret
                  key: MONGO_URI
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: order-service-secret
                  key: JWT_SECRET
            - name: RESTAURANT_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: order-service-secret
                  key: RESTAURANT_BASE_URL      
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "200m"

---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: ambula-lk
spec:
  selector:
    app: order-service
  ports:
    - port: 5003
      targetPort: 5003
  type: ClusterIP
