apiVersion: v1
kind: Secret
metadata:
  name: delivery-service-secret
  namespace: ambula-lk
type: Opaque
stringData:
  MONGODB_URI: mongodb+srv://hirunbhathiya:hirun123@food-delivery.rugwm.mongodb.net/
  JWT_SECRET: token_key
  CLOUDINARY_API_KEY: "114528482391895"
  CLOUDINARY_API_SECRET: "KN0ACWS4wFCB9cmuEfm-sPRpeYA"
  
---
apiVersion: v1
kind: Secret
metadata:
  name: payment-service-secret
  namespace: ambula-lk
type: Opaque
stringData:
  MONGODB_URI: mongodb+srv://hirunbhathiya:hirun123@food-delivery.rugwm.mongodb.net/
  JWT_SECRET: token_key
  PAYHERE_MERCHANT_ID: "1230186"
  PAYHERE_MERCHANT_SECRET: "MjE3MjE3MTI2OTI0OTY2Nzk1ODMzNTM3NzYwNjAyMTQ1MTk0NTcwOQ=="
  PAYHERE_RETURN_URL: "http://localhost:3000/payment/success"
  PAYHERE_CANCEL_URL: "http://localhost:3000/payment/cancel"
  PAYHERE_NOTIFY_URL: "http://localhost:5000/api/payments/callback"

 

